Do not use bare 'except'.
flake8 rule E722

Exception: as catchall, if
* the right thing to do does not depend on the error
* any error is reported or risen again.

git-svn-id: http://svn.code.sf.net/p/docutils/code/trunk/docutils@9033 929543f6-e4f2-0310-98a6-ba3bd3dd1d04